---

roles:
  - src: https://github.com/companieshouse/ansible-role-aws-nvme-device-files
    name: aws-nvme-device-files
    version: feature/python-3-support

  - src: https://github.com/companieshouse/ansible-role-elasticsearch
    name: elasticsearch
    version: feature/initial-implementation

  - src: https://github.com/geerlingguy/ansible-role-repo-epel
    name: epel
    version: 3.0.0

  - src: https://github.com/companieshouse/ansible-role-mounted-volume
    name: mounted-volume
    version: 1.0.5

  - src: https://github.com/geerlingguy/ansible-role-pip
    name: pip
    version: 2.0.0

  - src: https://github.com/cloudalchemy/ansible-node-exporter
    name: prometheus-node-exporter
    version: 0.22.0
